[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  # المكتبات المطلوبة لـ Netlify Function
  # مع PostgreSQL و express و serverless-http
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF netlify/"

# أولاً، نوجه طلبات API إلى دالة API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# نوجه كل الطلبات الأخرى إلى التطبيق
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  framework = "#custom"

# تحديد إصدار Node.js
[build.environment]
  NODE_VERSION = "18"

# معالجة CORS لطلبات API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Credentials = "true"

# إعدادات إضافية لأمان الموقع ولتحسين الأداء
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://*; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://*.netlify.app https://*.netlify.com"

# للتعامل مع SPA
[functions]
  node_bundler = "esbuild"